version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic

    ports:
      - "3306:3306"

  petclinic:
    image: petclinic

    container_name: petclinic-app

    ports:
      - "8080:8080"

    depends_on:
      - mysql


